"""Emit a Python module of typed field references from a catalog.

``python -m semql codegen --catalog mypkg.catalogs:default --out refs.py``
writes one class per cube whose attributes are :class:`~semql.refs.QualifiedRef`
constants (``orders.revenue``). Call sites then get editor autocomplete, and a
misspelt field becomes an unknown-attribute error the type checker reports —
the reference is validated against the catalog at generation time rather than
deferred to compile.

A ``QualifiedRef`` is a ``str`` subclass, so a generated constant drops
straight into a ``SemanticQuery`` (``measures=[orders.revenue]``) with no
conversion.
"""

from __future__ import annotations

import keyword
from collections.abc import Iterable

from semql.catalog import Catalog
from semql.model import Cube
from semql.refs import QualifiedRef, is_qualified

_HEADER = (
    "# Generated by `python -m semql codegen`. Do not edit by hand;\n"
    "# regenerate after changing the catalog.\n"
    "from semql import QualifiedRef\n"
)


def _cube_fields(cube: Cube) -> list[tuple[str, str]]:
    """``(category, field_name)`` for every referenceable field, in a stable
    declaration order so regeneration produces a byte-identical module."""
    fields: list[tuple[str, str]] = []
    fields += [("measure", m.name) for m in cube.measures]
    fields += [("dimension", d.name) for d in cube.dimensions]
    fields += [("time dimension", t.name) for t in cube.time_dimensions]
    fields += [("segment", s.name) for s in cube.segments]
    return fields


def _safe_attr(name: str) -> bool:
    """Whether ``name`` can be a Python class attribute. SQL identifiers are
    valid Python identifiers, but some (``from``, ``class``, ``import``) are
    Python keywords and cannot be attribute names."""
    return name.isidentifier() and not keyword.iskeyword(name)


def _emit_cube(cube: Cube) -> str:
    lines = [f"class {cube.name}:", f'    """Field references for the {cube.name!r} cube."""', ""]
    emitted = 0
    for category, field in _cube_fields(cube):
        ref = f"{cube.name}.{field}"
        if not is_qualified(ref):
            lines.append(f"    # skipped {field!r} ({category}): not an addressable cube.field ref")
            continue
        if not _safe_attr(field):
            # Reachable only as a string: a Python keyword can't be an
            # attribute, so name it in a comment rather than emit a SyntaxError.
            lines.append(
                f"    # skipped {field!r} ({category}): Python keyword — "
                f'reference it directly as "{ref}"'
            )
            continue
        lines.append(f'    {field}: QualifiedRef = QualifiedRef("{ref}")')
        emitted += 1
    if emitted == 0:
        lines.append("    pass")
    return "\n".join(lines)


def generate_refs_module(catalog: Catalog) -> str:
    """Return Python source declaring one class of ``QualifiedRef`` constants
    per cube in ``catalog``. The output is deterministic and compiles cleanly;
    a cube or field whose name is a Python keyword is skipped with a comment
    (still reachable as a plain ``"cube.field"`` string)."""
    cubes: Iterable[Cube] = catalog.as_dict().values()
    blocks = [_HEADER]
    for cube in cubes:
        if not _safe_attr(cube.name):
            blocks.append(
                f"# skipped cube {cube.name!r}: Python keyword — its fields are "
                f'still reachable as "{cube.name}.<field>" strings'
            )
            continue
        blocks.append(_emit_cube(cube))
    # Trailing newline; blank line between blocks.
    return "\n\n".join(blocks) + "\n"


# Re-exported for callers that want to build refs without codegen.
__all__ = ["generate_refs_module", "QualifiedRef"]
